name: Testes Automatizados (Jest, Cypress, k6)

on: [push, pull_request]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Node.js Configuration
        uses: actions/setup-node@v4
        with:
          node-version: 20.x 
          cache: 'npm'

      - name: Download Dependencies
        run: npm ci

      - name: Run Unit Tests (Jest)
        run: npm run test

      - name: Start Server in Background
        env:
          BASE_URL: 'http://localhost:3080'
          SUPABASE_URL: "https://xztrvvpxhccackzoaalz.supabase.co"
          SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dHJ2dnB4aGNjYWNrem9hYWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDYxNjUsImV4cCI6MjA3MDUyMjE2NX0.lNTBC-VzvHjvIydGUcg3uPb6leOIt78B6Zw6SeIa1zk"
        run: |
          npm install -g wait-on # Instala a ferramenta de espera
          echo "Iniciando servidor em background..."
          npm start &
          
          echo "Aguardando http://localhost:3080..."
          wait-on http://localhost:3080 -t 60000
          echo "Servidor está no ar!"

      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@v1

      - name: Run Load Test (Grafana k6)
        uses: grafana/run-k6-action@v1
        with:
          path: k6/cenario-doacao.js
        env:
          BASE_URL: 'http://localhost:3080'
          K6_USER_EMAIL: "guilherme.oliver@ba.estudante.senai.br"
          K6_USER_PASSWORD: "G@123456" 

      - name: Run Cypress Tests (E2E)
        continue-on-error: true 
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:3080'
          command: npm run cypress:run
        env:
          BASE_URL: 'http://localhost:3080'
          SUPABASE_URL: "https://xztrvvpxhccackzoaalz.supabase.co"
          SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dHJ2dnB4aGNjYWNrem9hYWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDYxNjUsImV4cCI6MjA3MDUyMjE2NX0.lNTBC-VzvHjvIydGUcg3uPb6leOIt78B6Zw6SeIa1zk"

      - name: Upload Cypress Artifacts
        if: failure() 
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots