name: Testes Automatizados (Jest, Cypress)

on: [push, pull_request]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Node.js Configuration
        uses: actions/setup-node@v4
        with:
          node-version: 23.x

      - name: Download Dependencies
        run: npm ci

      - name: Run Unit Tests (Jest)
        run: npm run test